-- Datos de demostración para el módulo de Editoriales
-- Este archivo contiene editoriales populares para probar el sistema

-- Insertar editoriales de ejemplo
INSERT INTO editoriales (editorial) VALUES
('Penguin Random House'),
('HarperCollins'),
('Simon & Schuster'),
('Macmillan Publishers'),
('Hachette Book Group'),
('Scholastic Corporation'),
('McGraw-Hill Education'),
('Pearson Education'),
('Oxford University Press'),
('Cambridge University Press'),
('Elsevier'),
('Wiley'),
('Springer Nature'),
('Taylor & Francis'),
('SAGE Publications'),
('Bloomsbury Publishing'),
('Workman Publishing'),
('Chronicle Books'),
('Abrams'),
('Disney Publishing Worldwide'),
('Marvel Comics'),
('DC Comics'),
('Dark Horse Comics'),
('Image Comics'),
('IDW Publishing'),
('Editorial Planeta'),
('Grupo Santillana'),
('Anaya'),
('Ediciones SM'),
('Vicens Vives'),
('Editorial Bruño'),
('McGraw-Hill Interamericana'),
('Pearson Educación'),
('Oxford University Press España'),
('Cambridge University Press España'),
('Editorial Teide'),
('Editorial Casals'),
('Editorial Everest'),
('Editorial Luis Vives'),
('Editorial Donostiarra'),
('Editorial Edebé'),
('Editorial Alhambra'),
('Editorial Akal'),
('Editorial Cátedra'),
('Editorial Gredos'),
('Editorial Taurus'),
('Editorial Alianza'),
('Editorial Ariel'),
('Editorial Crítica'),
('Editorial Paidós'),
('Editorial Anagrama'),
('Editorial Tusquets'),
('Editorial Seix Barral'),
('Editorial Lumen'),
('Editorial Alfaguara'),
('Editorial Austral'),
('Editorial Austral'),
('Editorial Espasa'),
('Editorial Aguilar'),
('Editorial El País'),
('Editorial Libros del Zorro Rojo'),
('Editorial Kalandraka'),
('Editorial Fondo de Cultura Económica'),
('Editorial Siglo XXI'),
('Editorial UNAM'),
('Editorial Trillas'),
('Editorial Limusa'),
('Editorial McGraw-Hill México'),
('Editorial Pearson México'),
('Editorial Prentice Hall'),
('Editorial Addison Wesley'),
('Editorial Benjamin Cummings'),
('Editorial Alfaomega'),
('Editorial Patria'),
('Editorial Esfinge'),
('Editorial Fernández Editores'),
('Editorial Publicaciones Cultural'),
('Editorial Progreso'),
('Editorial Grijalbo'),
('Editorial Diana'),
('Editorial Océano'),
('Editorial Larousse'),
('Editorial Salvat'),
('Editorial RBA'),
('Editorial Temas de Hoy'),
('Editorial Martínez Roca'),
('Editorial Plaza & Janés'),
('Editorial Destino'),
('Editorial Noguer'),
('Editorial Juventud'),
('Editorial Molino'),
('Editorial Bruguera'),
('Editorial Timun Mas'),
('Editorial Beascoa'),
('Editorial Montena'),
('Editorial Destino Infantil'),
('Editorial Combel'),
('Editorial Corimbo'),
('Editorial Thule'),
('Editorial A Buen Paso'),
('Editorial Milrazones'),
('Editorial Libre Albedrío'),
('Editorial Nórdica Libros'),
('Editorial Impedimenta'),
('Editorial Sexto Piso'),
('Editorial Periférica'),
('Editorial Alpha Decay'),
('Editorial Automática'),
('Editorial Fulgencio Pimentel'),
('Editorial Pepitas de Calabaza'),
('Editorial La Uña Rota'),
('Editorial El Desvelo'),
('Editorial Páginas de Espuma'),
('Editorial Candaya'),
('Editorial Pre-Textos'),
('Editorial Visor'),
('Editorial Hiperión'),
('Editorial Calambur'),
('Editorial Renacimiento'),
('Editorial Valparaíso'),
('Editorial Cátedra'),
('Editorial Castalia'),
('Editorial Edaf'),
('Editorial Siruela'),
('Editorial Minotauro'),
('Editorial Debolsillo'),
('Editorial Punto de Lectura'),
('Editorial Booket'),
('Editorial Zeta Bolsillo'),
('Editorial Temas de Hoy'),
('Editorial Martínez Roca'),
('Editorial Plaza & Janés'),
('Editorial Destino'),
('Editorial Noguer'),
('Editorial Juventud'),
('Editorial Molino'),
('Editorial Bruguera'),
('Editorial Timun Mas'),
('Editorial Beascoa'),
('Editorial Montena'),
('Editorial Destino Infantil'),
('Editorial Combel'),
('Editorial Corimbo'),
('Editorial Thule'),
('Editorial A Buen Paso'),
('Editorial Milrazones'),
('Editorial Libre Albedrío'),
('Editorial Nórdica Libros'),
('Editorial Impedimenta'),
('Editorial Sexto Piso'),
('Editorial Periférica'),
('Editorial Alpha Decay'),
('Editorial Automática'),
('Editorial Fulgencio Pimentel'),
('Editorial Pepitas de Calabaza'),
('Editorial La Uña Rota'),
('Editorial El Desvelo'),
('Editorial Páginas de Espuma'),
('Editorial Candaya'),
('Editorial Pre-Textos'),
('Editorial Visor'),
('Editorial Hiperión'),
('Editorial Calambur'),
('Editorial Renacimiento'),
('Editorial Valparaíso'),
('Editorial Cátedra'),
('Editorial Castalia'),
('Editorial Edaf'),
('Editorial Siruela'),
('Editorial Minotauro'),
('Editorial Debolsillo'),
('Editorial Punto de Lectura'),
('Editorial Booket'),
('Editorial Zeta Bolsillo');

-- Verificar las editoriales insertadas
SELECT 
    ideditorial,
    editorial,
    'Editorial creada exitosamente' as estado
FROM editoriales 
ORDER BY editorial;
